parameters:
  - name: environment
    displayName: Environment
    type: string
  - name: deployment_part
    displayName: Deployment Part
    type: string
  - name: packages
    displayName: Packages
    type: string

jobs:
  - deployment: app_deployment_${{ parameters.deployment_part }}
    displayName: Application Deployment for ${{ parameters.deployment_part }}
    ${{ if eq(parameters.deployment_part, 'part2') }}:
      dependsOn:
        - part1
        - part2
        - app_deployment_part1
    ${{ else }}:
      dependsOn:
        - part1
    workspace:
      clean: resources
    environment:
      name: "$(ProjectName)-${{ parameters.environment }}"
      tags: ${{ parameters.environment }},${{ parameters.deployment_part }}
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - checkout: templates

            - task: DownloadBuildArtifacts@0
              displayName: Download Build Artifacts From Azure
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: '$(build.BuildNumber)'
                itemPattern: '**/*.zip'
                downloadPath: '$(Agent.BuildDirectory)/DownloadBuildArtifacts'
                checkDownloadedFiles: true

            - task: PowerShell@2
              displayName: Pre-Check for the deployment
              inputs:
                filePath: $(Agent.BuildDirectory)/s/azure-devops-template/templates/deployment-controller/scripts/pre-checks.ps1
                arguments: |
                  -Environment ${{ parameters.environment }} `
                  -Packages '${{ parameters.packages }}' `
                  -BuildNumber '$(build.BuildNumber)' `
                  -CurrentBuildPath '$(build.artifactstagingdirectory)'